project:
  type: book
  output-dir: docs

book:
  title: "Stat 892: Writing and TA Prep"
  author: "Susan Vanderplas"
  date: "2022"
  toc: false
  number-depth: 1
  chapters:
    - index.qmd
    - 2022/Week1.qmd
    - 2022/Week2.qmd
    - 2022/Week3.qmd
    - 2022/Week4.qmd
    - 2022/Week5.qmd
    - 2022/Week6.qmd
    - 2022/Week7.qmd
    - 2022/Week8.qmd
    - 2022/Week9.qmd
    - 2022/Week10.qmd
    - 2022/Week11.qmd
    - 2022/Week12.qmd
    - 2022/Week13.qmd
    - 2022/Week14.qmd

  site-url: https://srvanderplas.github.io/unl-stat892-TAprep/
  repo-url: https://github.com/srvanderplas/unl-stat892-TAprep/
  repo-branch: main
  repo-actions: [edit]
  sharing: [twitter, facebook, linkedin]
  page-navigation: true
  page-footer:
    left: "Prepared for 2022, Susan Vanderplas"
    right:
      - icon: github
        href: https://github.com/srvanderplas
      - icon: twitter
        href: https://twitter.com/srvanderplas
  comments:
    giscus:
      repo: srvanderplas/unl-stat892-TAprep
      category: "General"
      mapping: "pathname"
  sidebar:
    style: floating
    collapse-level: 3
  search:
    location: navbar

date: today
date-format: long

from: markdown+emoji

number-depth: 3

format:
  pdf:
    documentclass: scrreport
    toc: false
  html:
    theme: cosmo





editor: source

# Knitr options
knitr:
  opts_chunk:
    collapse: true
    message: false
    warning: false
    error: true
    dpi: 300

execute:
  freeze: auto  # re-render only when source changes
